-- ============================================================
-- AIRPORT DATABASE
-- Database structure based on Laboratory Work 1
-- PostgreSQL / pgAdmin
-- ============================================================

-- STEP 1:
-- Create a database manually in pgAdmin:
-- CREATE DATABASE airport_db;
--
-- Then open Query Tool for airport_db and run this file.

-- ============================================================
-- CLEAN PREVIOUS TABLES
-- ============================================================

DROP TABLE IF EXISTS security_check CASCADE;
DROP TABLE IF EXISTS baggage_check CASCADE;
DROP TABLE IF EXISTS baggage CASCADE;
DROP TABLE IF EXISTS boarding_pass CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS passenger CASCADE;
DROP TABLE IF EXISTS flight CASCADE;
DROP TABLE IF EXISTS airline CASCADE;
DROP TABLE IF EXISTS airport CASCADE;

-- ============================================================
-- 1. AIRPORT
-- ============================================================

CREATE TABLE airport (
    airport_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport_name    VARCHAR(100) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    state           VARCHAR(100),
    city            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. AIRLINE
-- ============================================================

CREATE TABLE airline (
    airline_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline_code    VARCHAR(10) UNIQUE,
    name            VARCHAR(100) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 3. FLIGHT
-- ============================================================

CREATE TABLE flight (
    flight_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departing_gate          VARCHAR(10),
    arriving_gate           VARCHAR(10),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    airline_id              INTEGER NOT NULL REFERENCES airline(airline_id),
    departure_airport_id    INTEGER NOT NULL REFERENCES airport(airport_id),
    arrival_airport_id      INTEGER NOT NULL REFERENCES airport(airport_id),
    scheduled_departure     TIMESTAMP NOT NULL,
    scheduled_arrival       TIMESTAMP NOT NULL,
    actual_departure        TIMESTAMP,
    actual_arrival          TIMESTAMP
);

-- ============================================================
-- 4. PASSENGER
-- ============================================================

CREATE TABLE passenger (
    passenger_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name              VARCHAR(50) NOT NULL,
    last_name               VARCHAR(50) NOT NULL,
    gender                  VARCHAR(20),
    date_of_birth           DATE,
    country_of_citizenship  VARCHAR(100),
    country_of_residence    VARCHAR(100),
    passport_number         VARCHAR(30) UNIQUE,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 5. BOOKING
-- ============================================================

CREATE TABLE booking (
    booking_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id           INTEGER NOT NULL REFERENCES flight(flight_id) ON DELETE CASCADE,
    status              VARCHAR(30) NOT NULL,
    booking_platform    VARCHAR(30) NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ticket_price        NUMERIC(12,2) NOT NULL CHECK (ticket_price >= 0),
    passenger_id        INTEGER NOT NULL REFERENCES passenger(passenger_id) ON DELETE CASCADE
);

-- ============================================================
-- 6. BOARDING PASS
-- ============================================================

CREATE TABLE boarding_pass (
    boarding_pass_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat                VARCHAR(10) NOT NULL,
    boarding_time       TIMESTAMP,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    booking_id          INTEGER NOT NULL REFERENCES booking(booking_id) ON DELETE CASCADE
);

-- ============================================================
-- 7. BAGGAGE
-- ============================================================

CREATE TABLE baggage (
    baggage_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight_kg            NUMERIC(6,2) NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    booking_id           INTEGER NOT NULL REFERENCES booking(booking_id) ON DELETE CASCADE
);

-- ============================================================
-- 8. BAGGAGE CHECK
-- ============================================================

CREATE TABLE baggage_check (
    baggage_check_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result               VARCHAR(30) NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    booking_id           INTEGER NOT NULL REFERENCES booking(booking_id) ON DELETE CASCADE,
    passenger_id         INTEGER NOT NULL REFERENCES passenger(passenger_id) ON DELETE CASCADE
);

-- ============================================================
-- 9. SECURITY CHECK
-- ============================================================

CREATE TABLE security_check (
    security_check_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result              VARCHAR(30) NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passenger_id        INTEGER NOT NULL REFERENCES passenger(passenger_id) ON DELETE CASCADE
);

-- ============================================================
-- INITIAL AIRPORT DATA
-- ============================================================

INSERT INTO airport
(airport_name, country, state, city)
VALUES
('Almaty International Airport', 'Kazakhstan', 'Almaty Region', 'Almaty'),
('Astana International Airport', 'Kazakhstan', NULL, 'Astana'),
('Heathrow Airport', 'United Kingdom', NULL, 'London'),
('Haneda Airport', 'Japan', NULL, 'Tokyo'),
('Charles de Gaulle Airport', 'France', 'Ile-de-France', 'Paris'),
('Guarulhos International Airport', 'Brazil', 'Sao Paulo', 'Sao Paulo'),
('Warsaw Chopin Airport', 'Poland', 'Masovian', 'Warsaw'),
('Istanbul Airport', 'Turkey', 'Istanbul', 'Istanbul'),
('Mlawe Test Airport', 'Testland', NULL, 'Mlawe'),
('Kepuh Test Airport', 'Testland', NULL, 'Kepuh');

-- ============================================================
-- INITIAL AIRLINE DATA
-- Airline ID = 5 is intentionally created for task 13.
-- ============================================================

INSERT INTO airline
(airline_id, airline_code, name, country)
VALUES
(1, 'KZ1', 'Air Kazakhstan', 'Kazakhstan'),
(2, 'ALA', 'Almaty Airlines', 'Kazakhstan'),
(3, 'LON', 'London Air', 'United Kingdom'),
(4, 'TOK', 'Tokyo Air', 'Japan'),
(5, 'OLD', 'Old Airways', 'Germany'),
(6, 'PAR', 'Paris Air', 'France'),
(7, 'BRA', 'Brazil Air', 'Brazil'),
(8, 'POL', 'Poland Air', 'Poland');

-- ============================================================
-- 200 RANDOM PASSENGERS
-- ============================================================

INSERT INTO passenger
(first_name, last_name, gender, date_of_birth,
 country_of_citizenship, country_of_residence, passport_number)
SELECT
    'Name' || gs,
    'Surname' || gs,
    CASE
        WHEN random() < 0.5 THEN 'Male'
        ELSE 'Female'
    END,
    DATE '1980-01-01' + (random() * 13000)::INTEGER,
    CASE (random() * 4)::INTEGER
        WHEN 0 THEN 'Kazakhstan'
        WHEN 1 THEN 'Turkey'
        WHEN 2 THEN 'France'
        WHEN 3 THEN 'Japan'
        ELSE 'Poland'
    END,
    CASE (random() * 4)::INTEGER
        WHEN 0 THEN 'Kazakhstan'
        WHEN 1 THEN 'Turkey'
        WHEN 2 THEN 'United Kingdom'
        WHEN 3 THEN 'Brazil'
        ELSE 'Poland'
    END,
    'P' || LPAD(gs::TEXT, 7, '0')
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- 200 FLIGHTS
-- First 40 flights arrive in 2024.
-- This makes task 5 testable.
-- ============================================================

INSERT INTO flight
(departing_gate, arriving_gate, airline_id,
 departure_airport_id, arrival_airport_id,
 scheduled_departure, scheduled_arrival)
SELECT
    'D' || ((gs % 20) + 1),
    'A' || ((gs % 20) + 1),
    ((gs - 1) % 8) + 1,
    ((gs - 1) % 8) + 1,
    (gs % 8) + 1,
    CASE
        WHEN gs <= 40
        THEN TIMESTAMP '2024-01-01 08:00:00'
             + ((gs - 1) * INTERVAL '7 days')
        ELSE TIMESTAMP '2025-01-01 08:00:00'
             + ((gs - 41) * INTERVAL '3 days')
    END,
    CASE
        WHEN gs <= 40
        THEN TIMESTAMP '2024-01-01 12:00:00'
             + ((gs - 1) * INTERVAL '7 days')
        ELSE TIMESTAMP '2025-01-01 12:00:00'
             + ((gs - 41) * INTERVAL '3 days')
    END
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- 200 BOOKINGS
-- ============================================================

INSERT INTO booking
(flight_id, status, booking_platform, ticket_price, passenger_id)
SELECT
    gs,
    CASE
        WHEN gs % 4 = 0 THEN 'Cancelled'
        WHEN gs % 3 = 0 THEN 'Pending'
        ELSE 'Confirmed'
    END,
    CASE
        WHEN gs % 3 = 0 THEN 'Website'
        WHEN gs % 3 = 1 THEN 'Mobile'
        ELSE 'Agent'
    END,
    CASE
        WHEN gs % 7 = 0 THEN 8000 + (gs % 1000)
        WHEN gs % 5 = 0 THEN 12000 + (gs % 7000)
        ELSE 15000 + (gs % 30000)
    END,
    gs
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- 200 BOARDING PASSES
-- ============================================================

INSERT INTO boarding_pass
(seat, boarding_time, booking_id)
SELECT
    ((gs - 1) % 30 + 1)::TEXT ||
    CASE ((gs - 1) % 6)
        WHEN 0 THEN 'A'
        WHEN 1 THEN 'B'
        WHEN 2 THEN 'C'
        WHEN 3 THEN 'D'
        WHEN 4 THEN 'E'
        ELSE 'F'
    END,
    TIMESTAMP '2025-01-01 06:00:00'
        + (gs * INTERVAL '1 hour'),
    gs
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- 200 BAGGAGE RECORDS
-- ============================================================

INSERT INTO baggage
(weight_kg, created_at, updated_at, booking_id)
SELECT
    ROUND((5 + (gs % 26) + (gs % 10) / 10.0)::NUMERIC, 2),
    TIMESTAMP '2024-01-01 09:00:00'
        + (gs * INTERVAL '1 day'),
    TIMESTAMP '2024-01-01 09:00:00'
        + (gs * INTERVAL '1 day'),
    gs
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- 200 BAGGAGE CHECKS
--
-- 1-20  : before 2023-06-01 and Not checked
-- 21-40 : March 2024 and Not checked
-- This makes tasks 9 and 15 testable.
-- ============================================================

INSERT INTO baggage_check
(result, created_at, updated_at, booking_id, passenger_id)
SELECT
    CASE
        WHEN gs BETWEEN 21 AND 40 THEN 'Not checked'
        WHEN gs % 2 = 0 THEN 'Checked'
        ELSE 'Not checked'
    END,
    CASE
        WHEN gs <= 20
        THEN TIMESTAMP '2023-01-01 10:00:00'
             + (gs * INTERVAL '1 day')
        WHEN gs BETWEEN 21 AND 40
        THEN TIMESTAMP '2024-03-01 10:00:00'
             + ((gs - 21) * INTERVAL '1 day')
        ELSE TIMESTAMP '2025-01-01 10:00:00'
             + (gs * INTERVAL '1 day')
    END,
    CASE
        WHEN gs <= 20
        THEN TIMESTAMP '2023-01-01 10:00:00'
             + (gs * INTERVAL '1 day')
        WHEN gs BETWEEN 21 AND 40
        THEN TIMESTAMP '2024-03-01 10:00:00'
             + ((gs - 21) * INTERVAL '1 day')
        ELSE TIMESTAMP '2025-01-01 10:00:00'
             + (gs * INTERVAL '1 day')
    END,
    gs,
    gs
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- 200 SECURITY CHECKS
-- ============================================================

INSERT INTO security_check
(result, created_at, updated_at, passenger_id)
SELECT
    CASE
        WHEN gs % 2 = 0 THEN 'Checked'
        ELSE 'Not checked'
    END,
    TIMESTAMP '2025-01-01 11:00:00'
        + (gs * INTERVAL '1 day'),
    TIMESTAMP '2025-01-01 11:00:00'
        + (gs * INTERVAL '1 day'),
    gs
FROM generate_series(1, 200) AS gs;

-- ============================================================
-- CHECK THAT THE DATABASE WAS CREATED
-- ============================================================

SELECT 'airport' AS table_name, COUNT(*) AS rows_count
FROM airport
UNION ALL
SELECT 'airline', COUNT(*)
FROM airline
UNION ALL
SELECT 'flight', COUNT(*)
FROM flight
UNION ALL
SELECT 'passenger', COUNT(*)
FROM passenger
UNION ALL
SELECT 'booking', COUNT(*)
FROM booking
UNION ALL
SELECT 'boarding_pass', COUNT(*)
FROM boarding_pass
UNION ALL
SELECT 'baggage', COUNT(*)
FROM baggage
UNION ALL
SELECT 'baggage_check', COUNT(*)
FROM baggage_check
UNION ALL
SELECT 'security_check', COUNT(*)
FROM security_check
ORDER BY table_name;

